# Introduction

# Preparations

```{r}
library(dplyr)
library(ggplot2)
library(patchwork)
theme_set(hrbrthemes::theme_ipsum_rc())
```

```{r}
lm_with_scatter <- function(logx = TRUE, logy = FALSE) {
  l <- list(
    geom_point(size = 0.3),
    geom_smooth(method = "lm")
  )
  labs <- scales::label_number(scale_cut = scales::cut_short_scale())
  if (logx) l <- append(l, scale_x_log10(labels = labs))
  if (logy) l <- append(l, scale_y_log10(labels = labs))
  l
}

par(
  pch = 19,
  cex = 0.8,
  bty = "n"
)
```

# Getting the data

A relatively clean dataset with information on population size, GDP, and employment across a variety of sectors has been compiled from the OECD Data Explorer in the `build/build-dataset.R` script.

```{r}
dat <- duckplyr::read_parquet_duckdb("../data/processed/data.parquet")
```

# Getting to know the data

```{}
 1 M_N      Professional, scientific and technical activities; administrative a…
 2 L        Real estate activities
 3 J        Information and communication
 4 _T       Total - all activities
 5 C        Manufacturing
 6 OTQ      Public administration, defence, education, human health and social …
 7 A        Agriculture, forestry and fishing
 8 K        Financial and insurance activities
 9 GTI      Wholesale and retail trade; repair of motor vehicles and motorcycle…
10 F        Construction
11 RTU      Arts, entertainment and recreation; other service activities; activ…
12 BTE      Industry (except construction)
```

```{r, fig.width = 10, fig.height = 6}
dat <- dat |>
  mutate(
    finance = emp_K / emp__T,
    ict = emp_J / emp__T,
    proftech = emp_M_N / emp__T,
    pubadmin = emp_OTQ / emp__T,
    realest = emp_L / emp__T,
    trade_vehicles = emp_GTI / emp__T,
    construction = emp_F / emp__T,
    entertainment = emp_RTU / emp__T,
    industry = emp_BTE / emp__T,
    manufact = emp_C / emp__T,
    agricult = emp_A / emp__T
  )
```

# Urban scaling

```{r, fig.width = 10, fig.height = 7}
usa <- filter(dat, time == 2018, country == "USA")
plot(gdp_pc ~ log(pop), data = usa, pch = 19, cex = 0.8, frame = FALSE)
fit <- lm(gdp_pc ~ log(pop), data = usa)
abline(fit, col = "tomato")
```

```{r, fig.width = 10, fig.height = 6}
countries <- c("USA", "DEU", "FRA", "ITA", "ESP", "POL")
pd <- filter(dat, time == 2020, country %in% countries)
par(mfrow = c(2, 3), mar = c(5, 5, 2, 1))
for (ctry in countries) {
  usa <- filter(dat, time == 2018, country == ctry)
  plot(gdp_pc ~ log(pop), data = usa, pch = 19, cex = 0.8, frame = FALSE, main = ctry)
  fit <- lm(gdp_pc ~ log(pop), data = usa)
  abline(fit, col = "tomato")
}
```

```{r, fig.width = 10, fig.height = 7}
ggplot(pd, aes(pop, gdp_pc, color = fua)) +
  lm_with_scatter(logx=TRUE) +
  facet_wrap(~country, scales = "free")
```
